apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: project1-repo
  namespace: flux-system
spec:
  interval: 3m
  url: https://github.com/J0ne/project1_backend
  ref:
    branch: main